name: Reusable fuzzing workflow

on:
  workflow_call:
    inputs:
      problem:
        required: true
        type: string

jobs:
  common:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - name: Fuzz testing
        run: |
          go test -fuzz=Fuzz -fuzztime=55m ./${{ inputs.problem }}
