name: Median of Two Sorted Arrays

on: workflow_dispatch

jobs:
  fuzzing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
      - name: Fuzz testing
        run: |
          go test -fuzz=Fuzz -fuzztime=55m ./median-of-two-sorted-arrays
